hwi_oauth:
    resource_owners:
        keycloak:
            type:                keycloak
            base_url:            '%env(KEYCLOAK_SERVER_URL)%'
            realm:               '%env(KEYCLOAK_REALM)%'
            client_id:           '%env(KEYCLOAK_CLIENT_ID)%'
            client_secret:       '%env(KEYCLOAK_CLIENT_SECRET)%'
            # options:
            #     idp_hint:        <auth_hint_idp>
