version: "3.9"

services:
  app:
    image: "ghentcdh/dbbe:${DBBE_VERSION}"
    volumes:
      - ./.env.symfony:/app/.env
    ports:
      - "127.0.0.1:${DBBE_EXTERNAL_PORT:-8000}:80"
    # Add mount instruction to command if necessary:
    # mount -t cifs //<server>/<share> /app/data -o uid=application,gid=applicatioin,credentials=<credential_path>
    command: bash -c "composer dump-env prod && supervisord"
    restart: unless-stopped

  morph:
    image: perseidsproject/morpheus-perseids-api:v2.1.12
