version: "3.9"

services:
  app:
    image: "ghentcdh/dbbe:${DBBE_VERSION}"
    volumes:
      - ./.env.symfony:/app/.env
      # <host_path>:/app/data
    ports:
      - "127.0.0.1:${DBBE_EXTERNAL_PORT:-8000}:80"
    command: bash -c "composer dump-env prod && supervisord"
    restart: unless-stopped

  morph:
    image: perseidsproject/morpheus-perseids-api:v2.1.12
