version: "3.9"

services:
  app:
    build:
        context: .
        target: dev
    ports:
      - "127.0.0.1:${APP_SYMFONY_EXTERNAL_PORT:-8001}:8000"
    volumes:
      - ./:/app
      # images
      # page-images
    environment:
      DATABASE_URL: ${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT:-5432}/${DATABASE_NAME}?serverVersion=${DATABASE_VERSION}'
      ELASTIC_HOSTS: "{\"host\": \"${ELASTICSEARCH_HOST}\", \"port\": ${ELASTICSEARCH_PORT:-9200}}"
      ELASTIC_INDEX_PREFIX: ${ELASTICSEARCH_INDEX_PREFIX}
      MAILER_DSN: ${MAILER_DSN}
      SITEKEY: ${RECAPTCHA_SITEKEY}
      SECRETKEY: ${RECAPTCHA_SECRETKEY}
      RECAPTCHA_SITEVERIFY_URL: ${RECAPTCHA_SITEVERIFY_URL}
      MORPH_HOST: ${MORPH_HOST}
      PHP_MEMORY_LIMIT: 1024M
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    tty: true
    # First time: install dependencies
    # command: bash -c "composer install && pnpm install && cd assets/websites && ../../node_modules/bower/bin/bower --allow-root install && cd ../.. && pnpm encore dev && symfony server:start --no-tls"
    command: bash -c "symfony server:start --no-tls && sleep infinity"
    # command: bash -c "sleep infinity"
    depends_on:
      - database
      - elasticsearch
      - keycloak

  database:
    image: "postgres:${DATABASE_VERSION}-bookworm"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    container_name: "database"
    ports:
      - "127.0.0.1:${DATABASE_EXTERNAL_PORT:-15432}:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME

  elasticsearch:
    build:
        context: .
        dockerfile: elasticsearch.Dockerfile
    ports:
      - "127.0.0.1:${ELASTICSEARCH_EXTERNAL_PORT:-19200}:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      http.port: 9200
      transport.host: localhost
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  morph:
    image: perseidsproject/morpheus-perseids-api:v2.1.5
    ports:
      - "1500:1500"

  # Keycloak uses a postgres database
  keycloak_database:
    image: postgres:16.1-bookworm
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    ports:
      - "127.0.0.1:${KEYCLOAK_DATABASE_EXTERNAL_TCP_PORT}:${KEYCLOAK_DATABASE_INTERNAL_TCP_PORT}"
    volumes:
      - keycloak_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $KEYCLOAK_DATABASE_USER
      POSTGRES_PASSWORD: $KEYCLOAK_DATABASE_PASSWORD
      POSTGRES_DB: $KEYCLOAK_DATABASE_NAME

  # The keycloack service itself, depends on the availability of the database
  keycloak:
    image: keycloak/keycloak:23.0.6
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
    depends_on:
      - keycloak_database
    ports:
      - "127.0.0.1:${KEYCLOAK_EXTERNAL_TCP_PORT}:${KEYCLOAK_INTERNAL_TCP_PORT}"
    volumes:
      - ./keycloak-dev:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_database:${KEYCLOAK_DATABASE_INTERNAL_TCP_PORT}/$KEYCLOAK_DATABASE_NAME
      - KC_DB_USERNAME=$KEYCLOAK_DATABASE_USER
      - KC_DB_PASSWORD=$KEYCLOAK_DATABASE_PASSWORD

    command: start-dev --import-realm

volumes:
  database:
    external: true
    name: dbbe-database
  elasticsearch:
    external: true
    name: dbbe-elasticsearch
  keycloak_database:
    external: true
    name: dbbe-keycloak-database
