# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_provider]
        in_memory:
            memory:
                users:
                    __NO_USER__:
                        password:
                        roles: ROLE_ANO
        user_provider:
            id: user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|js)/
            security: false

        main:
            pattern: ^/
            security: true
            cas: true
            provider: chain_provider
            logout_on_user_change: true
            access_denied_url: /login

    role_hierarchy:
        ROLE_VIEW_INTERNAL: ROLE_USER
        ROLE_EDITOR_VIEW:   ROLE_VIEW_INTERNAL
        ROLE_EDITOR:        ROLE_EDITOR_VIEW
        ROLE_ADMIN:         ROLE_EDITOR
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
