# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_provider]
        in_memory:
            memory:
                users:
                    __NO_USER__:
                        password:
                        roles: ROLE_ANO
        user_provider:
            id: user_provider


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            cas: true
            pattern: ^/
            provider: chain_provider
            logout_on_user_change: true
            anonymous:    true

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_VIEW_INTERNAL: ROLE_USER
        ROLE_ADMIN:         ROLE_VIEW_INTERNAL
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    access_control:
        - { path: ^/admin/users, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
