# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            saml:
                # Match SAML attribute 'uid' with username.
                username_attribute: uid
                check_path: /saml/acs
                login_path: /saml/login
            logout:
                path: /saml/logout
            logout_on_user_change: true

    role_hierarchy:
        ROLE_VIEW_INTERNAL: ROLE_USER
        ROLE_EDITOR_VIEW:   ROLE_VIEW_INTERNAL
        ROLE_EDITOR:        ROLE_EDITOR_VIEW
        ROLE_ADMIN:         [ROLE_EDITOR, ROLE_JULIE]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
