security:
    providers:
        user_provider:
            id: App\Security\UserProvider
    firewalls:
        main:
            lazy: true
            provider: user_provider
            saml:
                # Match SAML attribute 'mail' with username.
                username_attribute: mail
#                user_factory: user_factory
                check_path: /saml/acs
                login_path: /saml/login
            logout:
                path: /saml/logout
            remember_me:
                secret:   '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                always_remember_me: true

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_VIEW_INTERNAL: ROLE_USER
        ROLE_EDITOR_VIEW:   ROLE_VIEW_INTERNAL
        ROLE_EDITOR:        ROLE_EDITOR_VIEW
        ROLE_ADMIN:         [ROLE_EDITOR, ROLE_JULIE]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
